### model
model_name_or_path: /scratch/hz4426/MiniCPM-o/MiniCPM-o-2_6 # 这里可以填入原始模型地址，可以是本地模型
adapter_name_or_path: /scratch/hz4426/LLaMA-Factory/saves/minicpmo_2_6/lora/frames_cropped_nov # 这里填入保存的lora模型地址
template: minicpm_v
finetuning_type: lora
trust_remote_code: true

### export
export_dir: models/minicpmo_2_6_lora_sft_frames_cropped_nov
export_size: 2
export_device: cpu
export_legacy_format: false